---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - home-assistant
  - mosquitto
  - node-red
  - octoprint
  - ring-mqtt
  - teslamate
  - unifi-browser
  - zigbee2mqtt
  - zwavejs2mqtt
